"""Initial schema: conversation_sessions and messages

Revision ID: 1f830d78be7f
Revises:
Create Date: 2026-06-20 02:37:47.302793

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1f830d78be7f'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.Column('messages_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_created', 'conversation_sessions', ['created_at'], unique=False)
    op.create_index('idx_session_user', 'conversation_sessions', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_created_at'), 'conversation_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_user_id'), 'conversation_sessions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('rag_query', sa.Boolean(), nullable=True),
    sa.Column('rag_relevant_chunks', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_message_created', 'messages', ['created_at'], unique=False)
    op.create_index('idx_message_session', 'messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index('idx_message_session', table_name='messages')
    op.drop_index('idx_message_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversation_sessions_user_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_created_at'), table_name='conversation_sessions')
    op.drop_index('idx_session_user', table_name='conversation_sessions')
    op.drop_index('idx_session_created', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###
